### PR TITLE
support opentelemetry

### PR DESCRIPTION
**Pull request by zdyj3170101136**
the clickhouse supported opentelemetry:
https://clickhouse.com/docs/en/operations/opentelemetry/

so i think the driver should support otel.

### CODE REVIEW

**Comment by gingerwizard** [comment]
Thanks @zdyj3170101136 this feels alittle tightly coupled. Have you considered using https://github.com/qustavo/sqlhooks ? e.g. https://github.com/DataDog/dd-trace-go/blob/main/contrib/go-pg/pg.v10/pg_go.go#L28

**Comment by gingerwizard** [comment]
Unlikely we will merge this in its current form as its quite intrusive. @genzgd for 2nd opinion.

**Comment by jkaflik** [comment]
Closing due to stale changes. I recommend hooking on a `database/sql` interface level.

**Comment by everythings-gonna-be-alright** [comment]
It doesn't support m1 🤦
`go.opentelemetry.io/otel/api/trace: cannot find module providing package go.opentelemetry.io/otel/api/trace`

**Pull request closed without merging**
