### PR TITLE
Avoid panic when decoding an array of tuple with nullable properties …

### PR DESCRIPTION
**Pull request by stephane-moreau**
Following a debugging session of issue #816 

It seems that the proposed change do fix the issue

### CODE REVIEW

**Comment by gingerwizard** [comment]
@stephane-moreau can you sign the CLA?

**Comment by stephane-moreau** [comment]
> @stephane-moreau can you sign the CLA?

Validation is in progress with my company, should be ok soon

**Comment by stephane-moreau** [comment]
> @stephane-moreau can you sign the CLA?

done

**Comment by gingerwizard** [comment]
I think this is very close @stephane-moreau but I think we need to insert nils if nullable i.e. 

```
if _, isNullable := c.(*Nullable); !isNullable {
					targetMap.SetMapIndex(reflect.ValueOf(colName), reflect.Zero(c.ScanType().Elem()))
				} else {
					targetMap.SetMapIndex(reflect.ValueOf(colName), reflect.Zero(c.ScanType()))
				}

```

I'm going to merge and follow up with a small PR and test. Thanks again.

**Pull request merged**
