### PR TITLE
Allow int64 switch to float

### PR DESCRIPTION
**Pull request by caiwc**
I think float type should allow more type conversion.

### CODE REVIEW

**Comment by kshvakov** [comment]
Hi, this is not a good idea

**Comment by caiwc** [comment]
We are implementing a function that insert data into a table of unknown field type. Since I just can use `proto.Struct` as the type of inserted data and `proto.Value` just support `float64` for number , so the number type data I got is all `float64`. 
my solution is  convert the float to `int64` if it is a whole number. But when I insert a the whole number to Float type column will be fail because of the limitation of type conversion. 
The ideal solution for us would be to float and int can be converted to each other and rasie errors if overflows

**Comment by kshvakov** [comment]
Use ClickHouse metadata (like `DESC table_name`) and check/convert types before inserting. That logic must be on application side, IMHO

**Comment by caiwc** [comment]
os,I see, thank you !

**Pull request closed without merging**
