### PR TITLE
Add RegisterDial function

### PR DESCRIPTION
**Pull request by c3mb0**
Add a function to enable the user to optionally register a custom dial function. Implementation mostly inspired by [mysql driver](https://github.com/go-sql-driver/mysql/blob/46351a8892976898935f653f5333782579a96fa5/driver.go#L49).

### CODE REVIEW

**Comment by kshvakov** [comment]
And what reasons can there be for register a custom Dial function?

**Comment by c3mb0** [comment]
We use it in production to cache DNS resolutions via [dnscache](https://github.com/rs/dnscache). Here's a sample implementation:

```
r := &dnscache.Resolver{Timeout: 10 * time.Second}
clickhouse.RegisterDial(func(network, address string, timeout time.Duration, config *tls.Config) (conn net.Conn, err error) {
	host, port, err := net.SplitHostPort(address)
	if err != nil {
		return nil, err
	}
	ips, err := r.LookupHost(context.TODO(), host)
	if err != nil {
		return nil, err
	}
	for _, ip := range ips {
		if config != nil {
			conn, err = tls.DialWithDialer(&net.Dialer{Timeout: timeout}, network, net.JoinHostPort(ip, port), config)
		} else {
			conn, err = net.DialTimeout(network, net.JoinHostPort(ip, port), timeout)
		}
		if err == nil {
			break
		}
	}
	return
})
```
It can also be used to register custom dialers or troubleshoot connection issues. The implementation is non-intrusive and useful for advanced use cases.

**Comment by kshvakov** [comment]
Can you rebase PR to V1?  I'll add this feature to V2

**Comment by kshvakov** [comment]
Added in V2 and [V1.5.4](https://github.com/ClickHouse/clickhouse-go/releases/tag/v1.5.4)

**Pull request closed without merging**
