### PR TITLE
Fix json with nil will get error

### PR DESCRIPTION
**Pull request by ACV-er**
resoved: #823

### CODE REVIEW

**Comment by gingerwizard** [comment]
Rather than test on the function level - we don't have any other tests like this. Can you do a high level set of inserts/queries which reproduce the issue please? Add to https://github.com/ClickHouse/clickhouse-go/blob/main/tests/json_test.go

**Comment by ACV-er** [comment]
> Rather than test on the function level - we don't have any other tests like this. Can you do a high level set of inserts/queries which reproduce the issue please? Add to https://github.com/ClickHouse/clickhouse-go/blob/main/tests/json_test.go

I don't know all the implementations very well, it's a bit of a hassle, I'll give it a try

**Comment by ACV-er** [comment]
> 


> Rather than test on the function level - we don't have any other tests like this. Can you do a high level set of inserts/queries which reproduce the issue please? Add to https://github.com/ClickHouse/clickhouse-go/blob/main/tests/json_test.go

Is it okay to submit a commit like this?

**Comment by gingerwizard** [comment]
OK post some JSON which recreates your issue @ACV-er - I'll write a test.

**Comment by gingerwizard** [comment]
@ACV-er our cloud CI tests wont pass for external contributors as you don't have access to cluster secrets. Needs to be fixed. I'll test locally today and merge. thanks again. Will make 2.4.2 - likely end of week.

**Pull request merged**
