### PR TITLE
Add acknowledgments to README.md

### PR DESCRIPTION
**Pull request by alexey-milovidov**
My first pull request to ClickHouse Go driver!

### CODE REVIEW

**Comment by kshvakov** [comment]
Unfortunately I can't accept this PR. At least the list of projects is incomplete, or rather it is not correct.

I can start with the [PGX](https://github.com/jackc/pgx) project, the design of which I have been talking about for the last 5 years, if you raise my messages in ClickHouse chats.

Next, I would highlight the [sqlx](https://github.com/jmoiron/sqlx) project, which simplifies working with `database/sql` and which I have been using every day for many years.

There is also an excellent [Python driver](https://github.com/mymarilyn/clickhouse-driver) by Kostya, in which you can spy on the implementation of types and it's easier than in the ClickHouse code:) And of course [clickhouse-cpp](https://github.com/ClickHouse/clickhouse-cpp) by Vasily Nemkov.

In addition, [several dozen people](https://github.com/ClickHouse/clickhouse-go/blob/master/contributors/list) have contributed to the development of Go driver.

I have one question, who is Ernado (go-faster)? Why should we write that we admire him?

**Comment by ernado** [comment]
After 3 years of inactivity, v2 version was released with significant boost of commits almost immediately after [go-faster/ch](https://github.com/go-faster/ch) announce, borrowing many architectural decisions, optimizations, approaches, naming or even bugs.

I've collected a bit of cases just for the context:
| Case | Commit         | File                                        | Source                                 | Description                                                                                                                                                                                                       |
|------|----------------|---------------------------------------------|----------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1    | [372bf6b][1-c] | [.github/workflows/run-tests.yml][1-f]      | [.github/workflows/e2e.yml][1-s]       | Copy-pasted end-to-end testing pipeline, partially removed later due to inability to incorporate it without [custom end-to-end testing facility from ch][1-d]                                                     |
| 2    | [01e6efa][2-c] | [lib/proto/table_columns.go][2-f]           | [proto/table_columns.go][2-s]          | Copy-pasted `TableColumns` definition with original random (generic) naming, I have no idea why I've named them "First" and "Second", it means nothing                                                                                                                                       |
| 3    | [828888c][3-c] | [lib/column/codegen/column_unsafe.tpl][3-f] | [proto/cmd/ch-gen-col/unsafe.tpl][3-s] | Incorrectly (it is unlikely to use `reflect.SliceHeader` here, it was [explicitly removed in go-faster/ch][3-d]) copy-pasted unsafe optimization, note the `const size = {{ .Size }} / 8`                         |
| 4    | [2cec79c][4-c] | [conn_handshake.go][4-f]                    | [handshake.go][4-s]                    | Term "handshake" [was only used][4-d] in go-faster/ch in context of client-server "hello" packet exchange. |

On fourth case I've just got bored and don't want to invest any effort in this investigation.

[1-c]: https://github.com/ClickHouse/clickhouse-go/pull/452/commits/372bf6b28eef27f70cdfb927fd6d28817edfc5ce
[1-f]: https://github.com/ClickHouse/clickhouse-go/blob/372bf6b28eef27f70cdfb927fd6d28817edfc5ce/.github/workflows/run-tests.yml
[1-s]: https://github.com/go-faster/ch/blob/461109975f6b6d14e286048e431bd76d04c33a1a/.github/workflows/e2e.yml
[1-d]: https://github.com/go-faster/ch/blob/461109975f6b6d14e286048e431bd76d04c33a1a/cht/cht.go#L210-L219 "The go-faster/ch/cht package, end-to-end testing facility for ClickHouse"

[2-c]: https://github.com/ClickHouse/clickhouse-go/pull/452/commits/01e6efa2e663d28ae817c3673173743f842a999d
[2-f]: https://github.com/ClickHouse/clickhouse-go/blob/01e6efa2e663d28ae817c3673173743f842a999d/lib/proto/table_columns.go
[2-s]: https://github.com/go-faster/ch/blob/461109975f6b6d14e286048e431bd76d04c33a1a/proto/table_columns.go#L5

[3-c]: https://github.com/ClickHouse/clickhouse-go/pull/452/commits/828888c4a95f88129cf723c177406a4034a64306
[3-f]: https://github.com/ClickHouse/clickhouse-go/blob/828888c4a95f88129cf723c177406a4034a64306/lib/column/codegen/column_unsafe.tpl
[3-s]: https://github.com/go-faster/ch/blob/461109975f6b6d14e286048e431bd76d04c33a1a/proto/cmd/ch-gen-col/unsafe.tpl
[3-d]: https://github.com/go-faster/ch/commit/b0d5c2c10e3fedad5254db4cff691649bb18f0c6#diff-0051706e6678c4c990483d5f646700a0cefa90b8618ed6878e8c7be663566635

[4-c]: https://github.com/ClickHouse/clickhouse-go/pull/452/commits/2cec79cc8931d50c7364daeecbe4c600b3ee2418
[4-f]: https://github.com/ClickHouse/clickhouse-go/blob/4234bb3ecbe1a5ad010221d9e13c6e61714718bf/conn_handshake.go
[4-s]: https://github.com/go-faster/ch/blob/461109975f6b6d14e286048e431bd76d04c33a1a/handshake.go
[4-d]: https://github.com/search?q=org%3AClickHouse+handshake&type=code

Looks like it is just a wonderful coincidence, same as [vahid-sohrabloo/chconn total rewrite](https://github.com/vahid-sohrabloo/chconn/commit/6b47b7e35cc4d88f532200a536b391c0a9cfdb08).

**Actually I don't want to be mentioned in README.md of this project at all, please close this PR.**

**Comment by alexey-milovidov** [comment]
@kshvakov I suggest to put all these references to the Acks in readme, similar to what you've posted here. It is not much from your side and it will make the project better. 

For example - I put links and references in the source code even for the cases when I'm inspired by some idea from a blog post. It is easy to do and it gives the proper appreciation for the authors, regardless of whether it is required by the license or not.

**Comment by alexey-milovidov** [comment]
> Actually I don't want to be mentioned in README.md

Ok.

**Pull request closed without merging**
