### PR TITLE
Fix send query on batch retry

### PR DESCRIPTION
**Pull request by EpicStep**
Hi, now `retry()` create empty connection, without `INSERT INTO` statement, because of this, it cannot be used.

### CODE REVIEW

**Comment by EpicStep** [comment]
Hi @jkaflik, I think some tests are flaky, this is true?

**Comment by jkaflik** [comment]
Hi @EpicStep 
Not really. This might be a regression with a recent ClickHouse version. I will be checking this.

**Comment by EpicStep** [comment]
> Hi @EpicStep
> Not really. This might be a regression with a recent ClickHouse version. I will be checking this.

Okey, thanks you

**Comment by jkaflik** [comment]
@EpicStep I will release this today

**Pull request merged**
