### PR TITLE
column support github.com/satori/go.uuid

### PR DESCRIPTION
**Pull request by Laotree**
#713

### CODE REVIEW

**Comment by gingerwizard** [comment]
Hesistant here - if we approve this we open the door to users adding any package they feel we should handle. This package does have a lot of usage however so I see the value - we are also very opinionated on google uuid (as is ch-go), so I see the argument. Is there any reason you can't just pass as a string though? this package supports `fmt.Stringer` and we could add `fmt.Stringer` to AppendRow  - this would feel more generic.

**Comment by Laotree** [comment]
> Hesistant here - if we approve this we open the door to users adding any package they feel we should handle. This package does have a lot of usage however so I see the value - we are also very opinionated on google uuid (as is ch-go), so I see the argument. Is there any reason you can't just pass as a string though? this package supports `fmt.Stringer` and we could add `fmt.Stringer` to AppendRow - this would feel more generic.

I use this package for a quick convert from string, and also because it's widely used by my colleagues.

it's supported in other orm tool packages such as postgresql or mysql. So, when I got an error in ck-go, I'm confused why it's not jus fine as expected. 

Yes, I can workaround by using google-uuid when connected with ck, and using satori-uuid when come with pg/mysql. However it will be weird to convert uuid when pass uuid between different databases.

If you don't want to add package by users, you could think about how to workaround in a more graceful way. Since it's so confused to get an error when using satori-uuid.

**Comment by gingerwizard** [comment]
> it's supported in other orm tool packages such as postgresql or mysql. So, when I got an error in ck-go, I'm confused why it's not jus fine as expected.

This isn't an orm package. Its a client/driver.

Are you using the `AppendRow` interface? If so, we can add support for `fmt.Stringer` - this will then transparently work. Likewise for `Scan`.

**Comment by Laotree** [comment]
> 

I used AppendStruct and Scan interfaces

Thanks for the comming support.

**Comment by gingerwizard** [comment]
@Laotree see https://github.com/ClickHouse/clickhouse-go/pull/720. Closing in favor of the more generic solution. Included test for satori uuid.

**Pull request closed without merging**
