### PR TITLE
Support Array(Nullable(T))

### PR DESCRIPTION
**Pull request by vl4deee11**
Added support for nullable arrays.

Code generation for append into reflect slice.

I did not use reflection for append into reflect slice, since it is twice as slow as code generation.

### CODE REVIEW

**Comment by vl4deee11** [comment]
@kshvakov Please help me with this PR😌

**Comment by vl4deee11** [comment]
@veqryn Please help me with this PR😌

**Comment by veqryn** [comment]
I am not actually a member of this repo, even though I have several PR's that were merged. I may be able to have a look when I get back in a couple weeks, but I don't have permission to merge so you are probably better off getting someone else to have a look. Good luck tho

**Comment by vl4deee11** [comment]
@veqryn Okay, thank you and good luck to you!

**Pull request merged**
