### PR TITLE
add error log and remote server address in clickhouse.go

### PR DESCRIPTION
**Pull request by taiyang-li**
Add error log and remote server address in clickhouse.go, making it more convenient to debug problems with clickhouse-server

### CODE REVIEW

**Comment by taiyang-li** [comment]
@kshvakov Can you help me with this PR? Thanks

**Comment by taiyang-li** [comment]
Any body here? Need your help..

**Comment by kshvakov** [comment]
Hi I have added this feature in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)

**Comment by taiyang-li** [comment]
Okay.

**Pull request closed without merging**
