### PR TITLE
Prepared statement added for AsyncWrite

### PR DESCRIPTION
**Pull request by emrekasg**

### CODE REVIEW

**Comment by kshvakov** [comment]
This is not very convenient, since bind parameters are very limited. Therefore, it is assumed that for asynchronous inserts, the user will generate SQL code on the side of his application

**Comment by emrekasg** [comment]
But as I know prepared statements prevents SQL injection, am I wrong? @kshvakov

**Comment by kshvakov** [comment]
Not for ClickHouse. ClickHouse does not support prepared queries

**Comment by emrekasg** [comment]
So, what's the way to prevent SQL injections in ClickHouse? Does this driver already prevent injections automatically?

**Comment by emrekasg** [comment]
I'm closing this pull request. Just learned this driver does use stdlib to escape string

**Pull request closed without merging**
