### PR TITLE
Add ability to pass custom type that has ToSQLArgument method as a query argument

### PR DESCRIPTION
**Pull request by f0mster**
Add ability to pass custom type that has `ToSQLArgument() string` method as a query argument.

### CODE REVIEW

**Comment by kshvakov** [comment]
The driver should not convert custom user types. You should do this in your app

**Comment by f0mster** [comment]
If so, maybe the driver should return an error if it's receive a type that it doesn't know?

**Comment by kshvakov** [comment]
No, if you want to convert something to a string, you must use the `Stringer` interface https://github.com/ClickHouse/clickhouse-go/blob/v2/bind.go#L140

**Comment by gingerwizard** [comment]
This does seem like something the driver should be doing.

**Pull request closed without merging**
