### PR TITLE
fix: fixed insert of decimals with non-standard exp representation

### PR DESCRIPTION
**Pull request by vogrelord**
## Summary
Fixed issue when insert of Decimal value 600 ended up with value 6 in database

## Checklist
Delete items not relevant to your PR:
- [x] Unit and integration tests covering the common scenarios were added
- [x] A human-readable description of the changes was provided to include in CHANGELOG

### CODE REVIEW

**Review by moming00 — APPROVED** [review]
good to me, thx

**Comment by jkaflik** [comment]
@vogrelord thanks for submitting. Will have a look tomorrow morning. 
cc @moming00

**Comment by moming00** [comment]
@jkaflik ，would you mind sharing the release plan?

**Comment by jkaflik** [comment]
@moming00 this will be included in todays release

**Comment by moming00** [comment]
> @moming00 this will be included in todays release

awesome, thx for that.

**Comment by jkaflik** [comment]
@moming00 https://github.com/ClickHouse/clickhouse-go/releases/tag/v2.6.2

**Pull request merged**
