### PR TITLE
Add driver.CollectRows and driver.AppendRows

### PR DESCRIPTION
**Pull request by EpicStep**
These auxiliary functions help with rows processing, examples of use can be seen in the tests

### CODE REVIEW

**Comment by EpicStep** [comment]
Hi @jkaflik. I think auxiliary functions that I published in this PR are inappropriate inside the database driver and it's better to put them in a separate repository, what do you think?

**Review by jkaflik — COMMENTED** [review]
I would rather defer it to a separate repository. If we want to keep this as a part of this, we need to consider it as a `util` subpackage.

**Comment by EpicStep** [comment]
Okey, sounds good, I will check this PR after vacation

**Comment by EpicStep** [comment]
A separate library is ready
https://github.com/EpicStep/clickhouse-go-rows-utils

**Pull request closed without merging**
