### PR TITLE
Run test in all subdirectories

### PR DESCRIPTION
**Pull request by orloffv**

### CODE REVIEW

**Comment by orloffv** [comment]
@gingerwizard current problem is - tests from subdirectories(issues, std) https://github.com/ClickHouse/clickhouse-go/tree/v2/tests never run in CI
Screen Shot 2022-05-25 at 17 53 35

**Comment by gingerwizard** [comment]
Nice catch. It seems we have a failure on an older version of ClickHouse - let me ascertain if that's an LTS we still want to support. We probably need to revisit the full test matrix as well - periodically on releases.

**Comment by gingerwizard** [comment]
I'm going to update the test matrix now and will then merge this @orloffv

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-go/pull/601 passes on latest versions. merging.

**Pull request merged**
