### PR TITLE
Support for Tuples and Histogram queries

### PR DESCRIPTION
**Pull request by mcgrawia**
Addressing issue #299 as well as #94. 

Big thanks to @stitchcula for the initial PR in #222. I based these features off that PR and updated it to work with Array(Tuple()). 

Please let me know if there are any changes I should make.

Thanks!

(replacing pr #300 from a dedicated branch)

### CODE REVIEW

**Comment by lming** [comment]
Any plan to merge this PR? We'd love to use `Array(Tuple)` in Go. Thanks.

**Comment by kshvakov** [comment]
Hi, sorry for the delay. Please fix the conflicts and update the PR

**Comment by mcgrawia** [comment]
hi @kshvakov, I've updated the PR and removed the conflicts. Let me know if there's anything else I can do 👍

**Comment by kshvakov** [comment]
Thank you!

**Pull request merged**
